# Generated by Django 4.0.5 on 2022-09-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
